### ISSUE TITLE
Deadlink in README

### ISSUE THREAD

**Issue by jmkristian** [mfncooper/paracon#4]
In the [README](https://github.com/mfncooper/paracon/blob/main/README.md), the phrase "Full documentation is available [online](https://pyham-paracon.readthedocs.io/en/latest/)" links to a 404 Not Found page. Perhaps it should link to [there](https://paracon.readthedocs.io/en/latest/userguide/).

**Comment by mfncooper** [comment]
Thanks for pointing that out. Fixed.
